---
name: "Feature request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
- type: markdown
  attributes:
    value: Before you open a new feature request, search through the existing feature requests to see if others have had the same idea.

- type: textarea
  id: describe-the-feature
  attributes:
    label: Describe the feature
  validations:
    required: true

- type: input
  id: ha-version
  attributes:
    label: Home Assistant version
    description: You can find your Home Assistant version in **Settings > About**.
    placeholder: |
      Example: "2025.7.2"
  validations:
    required: true

- type: input
  id: integration-version
  attributes:
    label: Integration version
    description: You can find this by going to **HACS > Google AQI.** The number beside the box is the version of the integration you are running.
    placeholder: |
      Example: "1.1.0"

- type: checkboxes
  attributes:
    label: Checklist
    options:
      - label: I have filled out the template to the best of my ability.
        required: true
      - label: This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
        required: true
      - label: This issue is not a duplicate feature request of [previous feature requests](https://github.com/bairnhard/home-assistant-google-aqi/labels/enhancement).
        required: true

- type: textarea
  attributes:
    label: "Additional context"
    description: "Add any other context or screenshots about the feature request here."
  validations:
    required: true